### ISSUE TITLE
Errors in the post meta box

### ISSUE THREAD

**Issue by mtndev** [congthien/tms#10]
I wanted to test the rectangular product images to make sure that this is working as expected. So I opened a product and edited the featured image using the post editor and only cropping the thumbnail. In the product gallery meta box there are some errors now that look related to the issue #9 . I don't see these errors when I apply the crop to all image sizes. So maybe when that gets fixed they will go away but I thought I ought to check w/ you to make sure. 

Thanks!

http://demo.famethemes.com/tms/wp-admin/post.php?post=143&action=edit

![image](https://cloud.githubusercontent.com/assets/11964029/14178268/1cc111b6-f717-11e5-8928-3b050f53433b.png)

**Comment by congthien** [comment]
Hi,

I rebuild the product image size now, so you don't need crop anymore. Please check again.

**Comment by mtndev** [comment]
When I click on a product thumb in the related products section, I still get the error on pageload. However when I reload it goes away. 

Here's what http://demo.famethemes.com/tms/wp-admin/post.php?post=139&action=edit loaded like:

![image](https://cloud.githubusercontent.com/assets/11964029/14207459/84e5ed3c-f7d7-11e5-8763-6aa23273266d.png)

I really like how you rebuilt the thumbs, thanks.

**Comment by mtndev** [comment]
It appeared consistently on the first time I viewed a product but after reloading, it's gone and doesn't appear on subsequent page views...can you reproduce the error?

**Comment by mtndev** [comment]
I originally tested in Chrome. I tried also in Firefox and it does the same thing...first view has the error, but gone on subsequent views on every product.

**Comment by congthien** [comment]
Hi there,
Don't worry about that. It is just a notice warning from WooCommerce because I enabled the debug mode. Now it is gone :)

**Comment by mtndev** [comment]
Ok sweet.

**Comment by mtndev** [comment]
Do you know if the undefined variable will cause any issues or what it is? Just curious.

**Comment by congthien** [comment]
Sometime it will cause of issues, but sometime is not. I don't know how to explain exactly :D . You can read here http://stackoverflow.com/questions/4261133/php-notice-undefined-variable-and-notice-undefined-index?answertab=active#tab-top
