### ISSUE TITLE
Homepage WC Products need to have rectangular dimensions

### ISSUE THREAD

**Issue by mtndev** [congthien/tms#4]
The products this client will list are books. The thumbnails will be the cover of the book which is rectangular. Is this something that will automatically adjusted based on the uploaded product image?

Just wanted to doublecheck with you.

Thanks!

Here's the screencap from the HTML mockup:

![image](https://cloud.githubusercontent.com/assets/11964029/14163062/dc9706f8-f6ae-11e5-8792-0a111e553e1b.png)

Here's the screencap of the current WP theme:

![image](https://cloud.githubusercontent.com/assets/11964029/14163086/157cc9da-f6af-11e5-9164-9372a2823040.png)

**Comment by congthien** [comment]
Hi,

Don't worry about this. I forget crop image before upload WooCommerce images. For now, it will be correct size when you upload new image :)
