### ISSUE TITLE
Question: How are the Partners logos added

### ISSUE THREAD

**Issue by mtndev** [congthien/tms#6]
The customizer has a place for the Partners text but I don't see anything for the images. Just let me know if I should add these manually to the page template or how you had planned for them to be updated.

Thanks!

![image](https://cloud.githubusercontent.com/assets/11964029/14163159/e39f53be-f6af-11e5-96f9-7306afe2de0a.png)

**Comment by mtndev** [comment]
I see this in template-frontpage.php now. That's fine w/ me. We can keep it like this if it's better for you.

![image](https://cloud.githubusercontent.com/assets/11964029/14163467/1410345c-f6b3-11e5-8016-b8b3ac8f58b2.png)

**Comment by congthien** [comment]
For partners image, I keep it like this :) . So you can add more images manually.
