### ISSUE TITLE
Add Sidebar widgets area to the customizer widgets list

### ISSUE THREAD

**Issue by mtndev** [congthien/tms#7]
It'd be great to have the Sidebar widgets area listed in the Customizer's widget areas list.

Here's how it currently looks in this version of the theme:

![image](https://cloud.githubusercontent.com/assets/11964029/14163278/196e401c-f6b1-11e5-9c87-04988259d3dd.png)

**Comment by congthien** [comment]
Hi,

The Sidebar widget area will be listed in Customize when you are in Page/ Post page. For home page, we have only footer, without sidebar.
