### ISSUE TITLE
functions and code switches between "tms" and "tsm" for prefixes

### ISSUE THREAD

**Issue by mtndev** [congthien/tms#8]
This might not matter at all since everything is working great, but it might cause some confusion in maintaining things later. if it's a quick fix now, it might be worth it. Open to your feedback.

TMS is the correct way (for The Masonry Society). Thanks!

![image](https://cloud.githubusercontent.com/assets/11964029/14163409/6496f236-f6b2-11e5-9d4c-62b17d4f233c.png)

**Comment by congthien** [comment]
Hi,

Sorry for my mistake. However, i think it doesn't matter :). Also, if I change it now, it will affect whole home page functions. so we should leave it :)
