### ISSUE TITLE
Doublecheck the spelling of product thumb function in fix

### ISSUE THREAD

**Issue by mtndev** [congthien/tms#9]
Hi I was just doublechecking the issue #1 and saw that issue #8 comes up: the fix spells the thumbnail function with tms but I checked and that function isn't defined anywhere and it's instead spelled tsm. So I think one or the other needs to be updated so they match. It'd be great if you have a way to do a global search/replace so you can make them all the same. Couldn't you search for everything that has tsm and change it to tms? That wouldn't break anything right?

Just wanted to check. Thanks!

![image](https://cloud.githubusercontent.com/assets/11964029/14177684/ad631cb2-f714-11e5-96ae-1ba9724800c2.png)

In template-frontpage.php https://github.com/congthien/tms/blob/00ed5cf1687a9959b11ad829794fe811eac8bfde/template-frontpage.php

![image](https://cloud.githubusercontent.com/assets/11964029/14177702/bee2903a-f714-11e5-9468-324aee9e5c0e.png)

**Comment by congthien** [comment]
i mean change all to tms prefix.

**Comment by mtndev** [comment]
Awesome. Thank you SO much for doing that.
